[package]
name = "glutin_core_graphics"
version = "0.1.0"
authors = ["The Servo Project Developers"]

[dependencies]
libc = "*"

[dependencies.core_foundation]
git = "https://github.com/servo/rust-core-foundation"

